-- MySQL Script generated by MySQL Workbench
-- 08/01/14 00:27:40
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tab_tipocaso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_tipocaso` (
  `tcas_id` INT NOT NULL AUTO_INCREMENT,
  `tcas_nom` VARCHAR(45) NULL,
  `tcas_desc` VARCHAR(45) NULL,
  `tcas_esta` VARCHAR(45) NULL,
  PRIMARY KEY (`tcas_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_area` (
  `area_id` INT NOT NULL AUTO_INCREMENT,
  `area_nom` VARCHAR(45) NULL,
  `area_desc` VARCHAR(45) NULL,
  `area_sigl` VARCHAR(45) NULL,
  `area_audi` VARCHAR(45) NULL,
  `area_esta` VARCHAR(45) NULL,
  PRIMARY KEY (`area_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_menu` (
  `menu_idop` INT NOT NULL AUTO_INCREMENT,
  `menu_nom` VARCHAR(45) NULL,
  `menu_desc` VARCHAR(45) NULL,
  `menu_esta` VARCHAR(45) NULL,
  PRIMARY KEY (`menu_idop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_tipousuario` (
  `tusu_idti` INT NOT NULL AUTO_INCREMENT,
  `tusu_nom` VARCHAR(45) NULL,
  `tusu_desc` VARCHAR(45) NULL,
  `tudu_esta` VARCHAR(45) NULL,
  PRIMARY KEY (`tusu_idti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_permiso` (
  `tab_tipousuario_tusu_idti` INT NOT NULL,
  `tab_menu_menu_idop` INT NOT NULL,
  INDEX `fk_tab_permiso_tab_tipousuario1_idx` (`tab_tipousuario_tusu_idti` ASC),
  INDEX `fk_tab_permiso_tab_menu1_idx` (`tab_menu_menu_idop` ASC),
  CONSTRAINT `fk_tab_permiso_tab_tipousuario1`
    FOREIGN KEY (`tab_tipousuario_tusu_idti`)
    REFERENCES `mydb`.`tab_tipousuario` (`tusu_idti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_permiso_tab_menu1`
    FOREIGN KEY (`tab_menu_menu_idop`)
    REFERENCES `mydb`.`tab_menu` (`menu_idop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_escritorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_escritorio` (
  `esc_id` INT NOT NULL AUTO_INCREMENT,
  `esc_nom` VARCHAR(45) NULL,
  `esc_audi` VARCHAR(45) NULL,
  `esc_esta` VARCHAR(45) NULL,
  PRIMARY KEY (`esc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_cliente` (
  `clte_id` INT NOT NULL AUTO_INCREMENT,
  `clte_nom1` VARCHAR(45) NULL,
  `clte_nom2` VARCHAR(45) NULL,
  `clte_ap1` VARCHAR(45) NULL,
  `clte_ap2` VARCHAR(45) NULL,
  `clte_apca` VARCHAR(45) NULL,
  `clte_dir` VARCHAR(45) NULL,
  `clte_tel` VARCHAR(45) NULL,
  `clte_mail` VARCHAR(45) NULL,
  `clte_nit` VARCHAR(10) NULL,
  `clte_esta` VARCHAR(45) NULL,
  PRIMARY KEY (`clte_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_usuario` (
  `usua_id` INT NOT NULL AUTO_INCREMENT,
  `usua_nom1` VARCHAR(45) NULL,
  `usua_nom2` VARCHAR(45) NULL,
  `usua_ap1` VARCHAR(45) NULL,
  `usua_ap2` VARCHAR(45) NULL,
  `usua_apca` VARCHAR(45) NULL,
  `usua_dir` VARCHAR(45) NULL,
  `usua_tel` VARCHAR(45) NULL,
  `usua_mail` VARCHAR(45) NULL,
  `usua_pass` VARCHAR(8) NULL,
  `tab_tipousuario_tusu_idti` INT NOT NULL,
  PRIMARY KEY (`usua_id`),
  INDEX `fk_tab_usuario_tab_tipousuario1_idx` (`tab_tipousuario_tusu_idti` ASC),
  CONSTRAINT `fk_tab_usuario_tab_tipousuario1`
    FOREIGN KEY (`tab_tipousuario_tusu_idti`)
    REFERENCES `mydb`.`tab_tipousuario` (`tusu_idti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_sesion` (
  `ses_id` INT NOT NULL AUTO_INCREMENT,
  `ses_fech` DATE NULL,
  `ses_hini` TIME NULL,
  `ses_hfin` TIME NULL,
  `tab_usuario_usua_id` INT NOT NULL,
  PRIMARY KEY (`ses_id`),
  INDEX `fk_tab_sesion_tab_usuario1_idx` (`tab_usuario_usua_id` ASC),
  CONSTRAINT `fk_tab_sesion_tab_usuario1`
    FOREIGN KEY (`tab_usuario_usua_id`)
    REFERENCES `mydb`.`tab_usuario` (`usua_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_turno` (
  `turn_idco` INT NOT NULL AUTO_INCREMENT,
  `turn_desc` VARCHAR(45) NULL,
  `turn_solu` VARCHAR(45) NULL,
  `turn_esta` VARCHAR(45) NULL,
  `turn_hini` TIME NULL,
  `turn_hfin` TIME NULL,
  `turn_audi` VARCHAR(45) NULL,
  `tab_area_area_id` INT NOT NULL,
  `tab_cliente_clte_id` INT NOT NULL,
  `tab_escritorio_esc_id` INT NOT NULL,
  `tab_tipocaso_tcas_id` INT NOT NULL,
  `tab_sesion_ses_id` INT NOT NULL,
  PRIMARY KEY (`turn_idco`),
  INDEX `fk_tab_turno_tab_area_idx` (`tab_area_area_id` ASC),
  INDEX `fk_tab_turno_tab_cliente1_idx` (`tab_cliente_clte_id` ASC),
  INDEX `fk_tab_turno_tab_escritorio1_idx` (`tab_escritorio_esc_id` ASC),
  INDEX `fk_tab_turno_tab_tipocaso1_idx` (`tab_tipocaso_tcas_id` ASC),
  INDEX `fk_tab_turno_tab_sesion1_idx` (`tab_sesion_ses_id` ASC),
  CONSTRAINT `fk_tab_turno_tab_area`
    FOREIGN KEY (`tab_area_area_id`)
    REFERENCES `mydb`.`tab_area` (`area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_turno_tab_cliente1`
    FOREIGN KEY (`tab_cliente_clte_id`)
    REFERENCES `mydb`.`tab_cliente` (`clte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_turno_tab_escritorio1`
    FOREIGN KEY (`tab_escritorio_esc_id`)
    REFERENCES `mydb`.`tab_escritorio` (`esc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_turno_tab_tipocaso1`
    FOREIGN KEY (`tab_tipocaso_tcas_id`)
    REFERENCES `mydb`.`tab_tipocaso` (`tcas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_turno_tab_sesion1`
    FOREIGN KEY (`tab_sesion_ses_id`)
    REFERENCES `mydb`.`tab_sesion` (`ses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
